### ISSUE TITLE
Can't compile on CentOS 6.6

### ISSUE THREAD

**Issue by andreasvc** [proycon/colibri-core#22]
I'm getting the following errors (gcc 4.4.7):

```
# pip3 install colibricore
[...]
    Bootstrapping colibri-core
    Autoconf archive found in /usr/share/aclocal/, good
    configure.ac:36: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
    ../../lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
    ../../lib/autoconf/general.m4:2661: _AC_LINK_IFELSE is expanded from...
    ../../lib/autoconf/general.m4:2678: AC_LINK_IFELSE is expanded from...
    /usr/share/aclocal/libtool.m4:1022: _LT_SYS_MODULE_PATH_AIX is expanded from...
    /usr/share/aclocal/libtool.m4:4161: _LT_LINKER_SHLIBS is expanded from...
    /usr/share/aclocal/libtool.m4:5236: _LT_LANG_C_CONFIG is expanded from...
    /usr/share/aclocal/libtool.m4:138: _LT_SETUP is expanded from...
    /usr/share/aclocal/libtool.m4:67: LT_INIT is expanded from...
    configure.ac:36: the top level
[...]
    libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -I../include -Wall -O3 -g -O2 -std=gnu++0x -MT pattern.lo -MD -MP -MF .deps/pattern.Tpo -c pattern.cpp  -fPIC -DPIC -o .libs/pattern.o
    In file included from ../include/patternstore.h:19,
                     from pattern.cpp:2:
    ../include/datatypes.h: In member function `std::string IndexReference::tostring() const':
    ../include/datatypes.h:73: error: call of overloaded `to_string(uint32_t)' is ambiguous
    /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2604: note: candidates are: std::string std::to_string(long long int)
    /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2610: note:                 std::string std::to_string(long long unsigned int)
    /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2616: note:                 std::string std::to_string(long double)
    ../include/datatypes.h:73: error: call of overloaded `to_string(unsigned int)' is ambiguous
    /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2604: note: candidates are: std::string std::to_string(long long int)
    /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2610: note:                 std::string std::to_string(long long unsigned int)
    /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2616: note:                 std::string std::to_string(long double)
    ../include/datatypes.h: In member function `void IndexedData::shrink_to_fit()':
    ../include/datatypes.h:151: error: `class std::vector<IndexReference, std::allocator<IndexReference> >' has no member named `shrink_to_fit'
    In file included from pattern.cpp:2:
    ../include/patternstore.h: In member function `void PatternSet<ReadWriteSizeType>::reserve(size_t)':
    ../include/patternstore.h:704: error: `class t_patternset' has no member named `reserve'
    pattern.cpp: In member function `const bool PatternPointer::unknown() const':
    pattern.cpp:408: warning: comparison between signed and unsigned integer expressions
    pattern.cpp: In constructor `Pattern::Pattern(std::istream*, bool, unsigned char, const unsigned char*, bool)':
    pattern.cpp:528: warning: comparison between signed and unsigned integer expressions
    make[2]: *** [pattern.lo] Error 1
    make[2]: Leaving directory `/home/avcrane1/src/colibri-core/tmp/pip-build-1al7wmwo/colibricore/src'
    make[1]: *** [all-recursive] Error 1
    make[1]: Leaving directory `/home/avcrane1/src/colibri-core/tmp/pip-build-1al7wmwo/colibricore'
    make: *** [all] Error 2
    Make of colibri-core failed
```

**Comment by proycon** [comment]
Sorry for the delay, I missed this issue...  
This is a compilation error I haven't encountered before yet and which I can't reproduce locally. I tried to commit a more explicit cast that should fix this hopefully. Can you try the latest version in this git master branch?

**Comment by proycon** [comment]
Closing this issue due to no activity in a long time, and CentOS 6 being too outdated in the meantime (use CentOS 8).
